### ISSUE TITLE
list archives api bug

### ISSUE THREAD

**Issue by korableg** [livechat/lc-sdk-go#106]
Hello!

According the reference of api (https://developers.livechat.com/docs/messaging/agent-chat-api#list-archives)
List archives should to get a page_id (string) parameter, instead of it lc_sdk_api passes the page number (uint) in paginaton object.

**example of json with bug:**
` {"filters":{"from":"1970-01-01T07:00:00.000000+07:00","tags":{"values":["test"],"require_every_value":true}},"pagination":{"page":2,"limit":100}}`

**right example:**
_first query:_
`{"filters":{"from":"1970-01-01T07:00:00.000000+07:00","tags":{"values":["test"],"require_every_value":true}}}`

_second_query (page_id from first)_
`{"page_id":"aeb9a763-2f6d-484b-69ff-b57ed9e34b13"}`

**Comment by korableg** [comment]
you can just take this PR: https://github.com/livechat/lc-sdk-go/pull/108

**Comment by grz-gajda** [comment]
In progress: https://github.com/livechat/lc-sdk-go/pull/113
