### ISSUE TITLE
Missed "chats" key in Customer struct

### ISSUE THREAD

**Issue by dgarbaczli** [livechat/lc-sdk-go#165]
In [https://github.com/livechat/lc-sdk-go/blob/5d6edf400dfcfdc1a9ea63785f0dc576b173f83a/agent/api.go#L305](url) 
struct Customer should has additional key. 
`get_customer` API method returns also:
 "chats": [
        {
            "chat_id": "XXX",
            "last_thread_started_at": "XXX"
        }
    ],
    
    which is not exist in Customer struct

**Comment by wfabjanczuk** [comment]
Hello, thanks for spotting that. I will fix that soon

**Comment by wfabjanczuk** [comment]
Hi again, it is fixed now. Check out the latest version and let me know if everything works for you now.
```bash
go get github.com/livechat/lc-sdk-go/v5@latest # github.com/livechat/lc-sdk-go/v5 v5.1.3
```

**Comment by dgarbaczli** [comment]
Hi. Everything works fine. Thank you
