### ISSUE TITLE
Rename ClientID to OwnerClientID in manageWebhooksStateRequest struct

### ISSUE THREAD

**Issue by lobiCode** [livechat/lc-sdk-go#66]
Based on the v3.3 [documentation](https://developers.livechat.com/docs/management/configuration-api/#enable-license-webhooks) the field `ClientID` should be renamed to `OwnerClientID`
https://github.com/livechat/lc-sdk-go/blob/v3.3/configuration/internal.go#L160

**Comment by janowsiany** [comment]
should be fixed, sorry for the inconvenience
